web/router.ex
defmodule Blox.Router do
  use Phoenix.Router

  pipeline :browser do
    plug :accepts, ~w(html)
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ~w(json)
  end

  scope "/", Blox do
    pipe_through :browser

    get "/", HomeController, :show

    resources "/posts", PostController do
      resources "/comments", CommentController, only: [:create, :delete]
    end
  end

  scope "/api/v1", Blox do
    pipe_through :api

    resources "/posts", PostController, only: [:index, :show]
  end
end

lib/blox/endpoint.ex
defmodule Blox.Endpoint do
  use Phoenix.Endpoint, otp_app: :blox

  plug Plug.Static,
    at: "/", from: :blox,
    only: ~w(css images js favicon.ico robots.txt)

  plug Plug.Logger

  if code_reloading? do
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader

    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
  end

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  plug Plug.Session,
    store: :cookie,
    key: "_blox_key",
    signing_salt: "thisisatestvalue"

  plug Blox.Router
end

lib/blox/protocol/phoenix/param/changeset.ex
defimpl Phoenix.Param, for: Ecto.Changeset do
  def to_param(changeset) do
    Phoenix.Param.to_param(changeset.data)
  end
end

lib/blox/protocol/poison/encoder/comment.ex
defimpl Poison.Encoder, for: Blox.Comment do
  def encode(comment, options) do
    %{
      id: comment.id,
      body: comment.body
    } |> Poison.Encoder.encode(options)
  end
end

lib/blox/protocol/poison/encoder/post.ex
defimpl Poison.Encoder, for: Blox.Post do
  def encode(post, options) do
    %{
      id: post.id,
      title: post.title,
      body: post.body,
      comments: post.comments
    } |> Poison.Encoder.encode(options)
  end
end

lib/blox/repo.ex
defmodule Blox.Repo do
  use Ecto.Repo, otp_app: :blox
  use Scrivener, page_size: 10
end

lib/blox/supervisor.ex
defmodule Blox.Supervisor do
  use Supervisor

  def start_link do
    Supervisor.start_link(__MODULE__, [])
  end

  def init([]) do
    children = [
      worker(Blox.Endpoint, []),
      worker(Blox.Repo, [])
    ]

    supervise(children, strategy: :one_for_one)
  end
end

lib/mix/tasks/db/populate.ex
defmodule Mix.Tasks.Db.Populate do
  use Mix.Task

  alias Blox.Post

  def run(_args) do
    Mix.Task.run("app.start", [])

    %Post{
      title: "Elixir is great",
      body: "Here is a bunch of info about Elixir."
    } |> Blox.Repo.insert!

    %Post{
      title: "Something about containers",
      body: "We should totally contain stuff in other stuff. Immutable infrastructure."
    } |> Blox.Repo.insert!
  end
end

lib/mix/tasks/db/reset.ex
defmodule Mix.Tasks.Db.Reset do
  use Mix.Task

  def run(_args) do
    Logger.configure(level: :error)

    Mix.Task.run("ecto.drop", [])
    Mix.Task.run("ecto.create", [])
    Mix.Task.run("ecto.migrate", [])

    if Mix.env == :dev do
      Mix.Task.run("db.populate", [])
    end
  end
end

web/models/comment.ex
defmodule Blox.Comment do
  use Ecto.Schema
  import Ecto.Changeset

  alias Blox.Post

  schema "comments" do
    field :body, :string

    belongs_to :post, Post

    timestamps
  end

  def changeset(comment, params \\ %{}) do
    comment
    |> cast(params, [:body])
    |> validate_required([:body])
  end
end

web/models/post.ex
defmodule Blox.Post do
  use Ecto.Schema

  import Ecto.Changeset
  import Ecto.Query

  alias Blox.Comment

  schema "posts" do
    field :title, :string
    field :body,  :string

    has_many :comments, Comment

    timestamps
  end

  def changeset(post, params \\ %{}) do
    post
    |> cast(params, [:title, :body])
    |> validate_required([:title, :body])
  end

  def order_by_date(query) do
    order_by(query, [p], desc: p.updated_at)
  end

  def with_comments(query) do
    preload(query, :comments)
  end
end

web/controllers/comment_controller.ex
defmodule Blox.CommentController do
  use Blox.Web, :controller

  alias Blox.Comment
  alias Blox.Post

  plug :scrub_params, "comment" when action in [:create]
  plug :find_post

  def create(conn, %{"comment" => params}) do
    changeset =
      conn.assigns[:post]
      |> build_assoc(:comments)
      |> Comment.changeset(params)

    case Blox.Repo.insert(changeset) do
      {:ok, comment} ->
        redirect conn, to: post_path(conn, :show, comment.post_id)

      {:error, changeset} ->
        render conn, :new, changeset: changeset
    end
  end

  def delete(conn, %{"id" => id}) do
    post = conn.assigns[:post]

    post
    |> assoc(:comments)
    |> Blox.Repo.get(id)
    |> Blox.Repo.delete!

    redirect conn, to: post_path(conn, :show, post)
  end

  def find_post(conn, _opts) do
    post = Blox.Repo.get(Post, conn.params["post_id"])

    if post do
      assign(conn, :post, post)
    else
      conn
      |> put_flash(:error, "Post not found")
      |> redirect(to: post_path(conn, :index))
      |> halt
    end
  end
end

web/controllers/home_controller.ex
defmodule Blox.HomeController do
  use Blox.Web, :controller

  def show(conn, _params) do
    render conn, :show
  end
end

web/controllers/post_controller.ex
defmodule Blox.PostController do
  use Blox.Web, :controller

  alias Blox.Comment
  alias Blox.Post

  plug :scrub_params, "post" when action in [:create, :update]

  def create(conn, %{"post" => params}) do
    changeset = Post.changeset(%Post{}, params)

    case Blox.Repo.insert(changeset) do
      {:ok, post} ->
        redirect conn, to: post_path(conn, :show, post)

      {:error, changeset} ->
        render conn, :new, changeset: changeset
    end
  end

  def delete(conn, %{"id" => id}) do
    Post
    |> Blox.Repo.get(id)
    |> Blox.Repo.delete!

    redirect conn, to: post_path(conn, :index)
  end

  def edit(conn, %{"id" => id}) do
    changeset =
      Post
      |> Blox.Repo.get(id)
      |> Post.changeset

    render conn, :edit,
      changeset: changeset
  end

  def index(conn, _params) do
    posts =
      Post
      |> Post.order_by_date
      |> Post.with_comments
      |> Blox.Repo.all

    render conn, :index,
      posts: posts
  end

  def new(conn, _parms) do
    changeset = Post.changeset(%Post{})

    render conn, :new,
      changeset: changeset
  end

  def show(conn, %{"id" => id}) do
    post =
      Post
      |> Post.with_comments
      |> Blox.Repo.get(id)

    new_comment =
      post
      |> build_assoc(:comments)
      |> Comment.changeset

    render conn, :show,
      new_comment: new_comment,
      post: post
  end

  def update(conn, %{"id" => id, "post" => params}) do
    changeset =
      Post
      |> Blox.Repo.get(id)
      |> Post.changeset(params)

    case Blox.Repo.update(changeset) do
      {:ok, post} ->
        redirect conn, to: post_path(conn, :show, post)

      {:error, changeset} ->
        render conn, :edit, changeset: changeset
    end
  end
end

web/views/comment_view.ex
defmodule Blox.CommentView do
  use Blox.Web, :view
end

web/views/error_view.ex
defmodule Blox.ErrorView do
  use Blox.Web, :view

  def render("404.html", _assigns) do
    "Page not found - 404"
  end

  def render("500.html", _assigns) do
    "Server internal error - 500"
  end

  def template_not_found(_, assigns) do
    render "500.html", assigns
  end
end

web/views/home_view.ex
defmodule Blox.HomeView do
  use Blox.Web, :view
end

web/views/layout_view.ex
defmodule Blox.LayoutView do
  use Blox.Web, :view
end

web/views/post_view.ex
defmodule Blox.PostView do
  use Blox.Web, :view

  def render("index.json", %{page: page}) do
    page.entries
  end

  def render("show.json", %{post: post}) do
    post
  end
end

web/views/shared_view.ex
defmodule Blox.SharedView do
  use Blox.Web, :view
end

web/templates/comment/new.html.eex
<%= render Blox.SharedView, "_errors.html", Dict.merge(assigns, errors: @changeset.errors) %>

<%= form_for @changeset, :create, fn f -> %>
  <%= text_input f, :body %>

  <%= submit "Create" %>
<% end %>

web/templates/home/show.html.eex
<h1>Welcome to Blox</h1>

<%= link "View Posts", to: post_path(@conn, :index) %>

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Blox</title>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta id="_csrf_token" content="<%= get_csrf_token %>">

    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>" />

    <script type="text/javascript" src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </head>

  <body>
    <%= render @view_module, @view_template, assigns %>
    <script>require("web/static/js/app");</script>
  </body>
</html>

web/templates/layout/application.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Blox</title>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta id="_csrf_token" content="<%= get_csrf_token %>">

    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>" />

    <script type="text/javascript" src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </head>

  <body>
    <%= @inner %>
    <script>require("web/static/js/jquery-ujs");</script>
  </body>
</html>

web/templates/post/_form.html.eex
<%= text_input @f, :title %>
<%= text_input @f, :body %>

web/templates/post/edit.html.eex
<%= render Blox.SharedView, "_errors.html", Dict.merge(assigns, errors: @changeset.errors) %>

<%= form_for @changeset, post_path(@conn, :update, @changeset), fn f -> %>
  <%= render Blox.PostView, "_form.html", Dict.merge(assigns, f: f) %>

  <%= submit "Update" %>
<% end %>

web/templates/post/index.html.eex
<ul>
<%= for post <- @page.entries do %>
  <li>
    <%= link post.title, to: post_path(@conn, :show, post) %>
  </li>
<% end %>
</ul>

<div>
  <%= link "New Post", to: post_path(@conn, :new) %>
</div>

web/templates/post/new.html.eex
<%= render Blox.SharedView, "_errors.html", Dict.merge(assigns, errors: @changeset.errors) %>

<%= form_for @changeset, post_path(@conn, :create), fn f -> %>
  <%= render Blox.PostView, "_form.html", Dict.merge(assigns, f: f) %>

  <%= submit "Create" %>
<% end %>

web/templates/post/show.html.eex
<h1><%= @post.title %></h1>
<div>
  <pre>
    <%= @post.body %>
  </pre>
</div>

<div>
  <h2>Comments</h2>
  <ul>
    <%= for comment <- @post.comments do %>
      <li>
        <%= comment.body %> -
        <%= link "Delete", to: post_comment_path(@conn, :delete, @post, comment), "data-remote": true, "data-confirm": true, "data-method": "DELETE" %>
      </li>
    <% end %>
  </ul>
</div>

<div>
  <h2>Add Comment</h2>
  <%= form_for @new_comment, post_comment_path(@conn, :create, @post), fn f -> %>
    <%= text_input f, :body %>
    <%= submit "Create" %>
  <% end %>
</div>

<ul>
  <li>
    <%= link "Edit", to: post_path(@conn, :edit, @post) %>
  </li>
  <li>
    <%= link "Delete", to: post_path(@conn, :delete, @post), "data-remote": true, "data-confirm": true, "data-method": "DELETE" %>
  </li>
  <li>
    <%= link "View All Posts", to: post_path(@conn, :index) %>
  </li>
</ul>

web/templates/shared/_errors.html.eex
<%= if @errors != [] do %>
<div>Errors!</div>
<% end %>